GET http://localhost:3001/users/3 HTTP/1.1
Authorization: bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdvbGlAZC5jb20iLCJzdWIiOjEsIm5hbWUiOiJnb2xpIERvZSIsInJvbGUiOnsiaWQiOjEsIm5hbWUiOiJPd25lciIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjRUMDY6MjU6NTEuMTEzWiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjRUMDY6MjU6NTEuMTEzWiJ9LCJpYXQiOjE2NjY2NzcxMzUsImV4cCI6MTY2OTI2OTEzNX0.Gjmg_sv0afVg80lgn5WdgYP_1SAfE_zNrwvIAaUyXB0