GET http://localhost:3001/users?page=1&size=1&sort=asc HTTP/1.1
Content-Type: application/jsonsIm5hbWUiOiJPd25lciIs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdvbGlAZC5jb20iLCJzdWIiOjEsIm5hbWUiOiJnb2xpIiwicm9sZSI6eyJpZCI6MSwibmFtZSI6Ik93bmVyIiwiY3JlYXRlZEF0IjoiMjAyMi0xMS0xNFQxMDowMToxNy4xOTNaIiwidXBkYXRlZEF0IjoiMjAyMi0xMS0xNFQxMDowMToxNy4xOTNaIn0sImlhdCI6MTY2ODUzMTY4MiwiZXhwIjoxNjcxMTIzNjgyfQ.o1fXqqrQWKEKdZUCL2kiJeQjXB5xiUdP-XCwkvmYiuk