GET http://localhost:3001/employee HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdvbGlAZC5jb20iLCJzdWIiOjEsIm5hbWUiOiJnb2xpIERvZSIsInJvbGUiOnsiaWQiOjEsIm5hbWUiOiJPd25lciIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjRUMDE6MDQ6MzYuMjQzWiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjRUMDE6MDQ6MzYuMjQzWiJ9LCJpYXQiOjE2NjY1ODYxNDgsImV4cCI6MTY2OTE3ODE0OH0.B030RjFFmy4DitPpO9BaVzWPSRTHYqnZVoKzNXcil1k