PUT http://localhost:3001/users/2 HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhZG1laHIxMjNAZ21haWwuY29tIiwic3ViIjoyLCJuYW1lIjoicmFkIG1laHIiLCJyb2xlIjp7ImlkIjoyLCJuYW1lIjoiRW1wbG95ZWUiLCJjcmVhdGVkQXQiOiIyMDIyLTEyLTA0VDA0OjU4OjMwLjEwMVoiLCJ1cGRhdGVkQXQiOiIyMDIyLTEyLTA0VDA0OjU4OjMwLjEwMVoifSwiaWF0IjoxNjcwMzUwNzU4LCJleHAiOjE2NzI5NDI3NTh9.YU6EXO76hdcMFBdQ5oQgO25axAZFVbti9Ug-rEYqk94

{

    "oldPassword": "0000",
    "newPassword": "7777"
    
    
}