PUT http://localhost:3001/users/33 HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJzdWIiOjMzLCJuYW1lIjoiYmFuZG0iLCJyb2xlIjp7ImlkIjoxLCJuYW1lIjoiT3duZXIiLCJjcmVhdGVkQXQiOiIyMDIyLTExLTEzVDA1OjE0OjM1LjMzNloiLCJ1cGRhdGVkQXQiOiIyMDIyLTExLTEzVDA1OjE0OjM1LjMzNloifSwiaWF0IjoxNjY4Mzk1MDc0LCJleHAiOjE2NzA5ODcwNzR9.Z5TBg_B1BaZdtykuioCzvzem-QupbOdTcQYXUzL8t0E

{

    "oldPassword": "0000",
    "newPassword": "3333"
    
    
}