DELETE   http://localhost:3001/notes/18 HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhpQGQuY29tIiwic3ViIjo1LCJuYW1lIjoiaGkgRG9lIiwicm9sZSI6bnVsbCwiaWF0IjoxNjY1ODMwMzYzLCJleHAiOjE2Njg0MjIzNjN9.ppk6SKccKqjVbH1mxd35ehDjs43C4jD11DWw_JsV0ig
    