GET http://localhost:3001/notes/2 HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtlcmlvQGxvLmFnZW5jeSIsInN1YiI6MiwibmFtZSI6ImtlcmlvIERvZSIsImlhdCI6MTY2NDk2Mzk3NCwiZXhwIjoxNjY3NTU1OTc0fQ.ZJnuLVQ10RHAN90JdHig-lnGplbnEHPGq-3XfoIiLB8