GET http://localhost:3001/invites/90897f478de161fffe393d1631cdfbb6720ef4114d679715f2ecd85a4990cc7d1bb7244ee6aea576222f73e37b811381 HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhcmFAZC5jb20iLCJzdWIiOjE3LCJuYW1lIjoic2FyYURvZSIsImlhdCI6MTY2NjI3NjU0NSwiZXhwIjoxNjY4ODY4NTQ1fQ.C0jZsrU16bVIPjIOtM9oFFku60utOzz8iSRgpX71eW0
