GET http://localhost:3001/invites/ba54be0ef7127ada6d85ce7de0edc7e110c24dd6fac26e4a71498e3b21b3c5e2a1a32edcd2d705ebfb8de225b0469dcf HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNoYWRpQGQuY29tIiwic3ViIjoyMCwibmFtZSI6InNoYWQgRG9lIiwicm9sZSI6eyJpZCI6MSwibmFtZSI6Ik93bmVyIiwiY3JlYXRlZEF0IjoiMjAyMi0xMC0yNVQwMjozMDo0Ny40OThaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0yNVQwMjozMDo0Ny40OThaIn0sImlhdCI6MTY2Njc2NDI0OCwiZXhwIjoxNjY5MzU2MjQ4fQ.IE2eaaqZUJ29uxkE81_dZDGvZUzcrSab7C-wy7CHmXM