POST http://localhost:3001/invites HTTP/1.1
Content-Type: application/json
Authorization: bearer 
Authorization: bearer 

{
	"invites": [
		{
			"name": "Mary",
			"email": "maryam.pourganji92@gmail.com"
		}
	]
}