POST http://localhost:3001/invites HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFmdGVyZGVhdGhAZC5jb20iLCJzdWIiOjY4LCJuYW1lIjoiZGMgRG9lIiwicm9sZSI6eyJpZCI6MSwibmFtZSI6Ik93bmVyIiwiY3JlYXRlZEF0IjoiMjAyMi0xMC0yM1QwMzoxMjo1Mi45MDFaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0yM1QwMzoxMjo1Mi45MDFaIn0sImlhdCI6MTY2ODAwOTIzNiwiZXhwIjoxNjcwNjAxMjM2fQ.CYoszlE91bl477Hxajifc5a2ohbfiK1IC8kObJu8x34

{
	"invites": [
		{ 
			"name": "aien987 saedi",
			"email": "aien8977@gmail.com"
		}
	]
}