
POST http://localhost:3001/contacts HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFpZW4rdGVzdDFAbG8uYWdlbmN5Iiwic3ViIjoxLCJuYW1lIjoiZ29sIERvZSIsImlhdCI6MTY2NDM3OTg2MSwiZXhwIjoxNjY2OTcxODYxfQ.YXFco9imWLau2zEa-qb_0hET3tHOilPu8iryDD6wsPs

{
	"email": "peach@lo.agency",
    "name": "banana Baltazar",
    "phone": "09123456789",
    "status": "Lead"
}
//user goli@d.com