
POST http://localhost:3001/contacts HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdvbGlAZC5jb20iLCJzdWIiOjEsIm5hbWUiOiJnb2xpIiwicm9sZSI6eyJpZCI6MSwibmFtZSI6Ik93bmVyIiwiY3JlYXRlZEF0IjoiMjAyMi0xMi0wMVQxMzoxMTowMi41NTRaIiwidXBkYXRlZEF0IjoiMjAyMi0xMi0wMVQxMzoxMTowMi41NTRaIn0sImlhdCI6MTY2OTkxMzkyOCwiZXhwIjoxNjcyNTA1OTI4fQ.SAwve02_L_1WR4RPhau75c76ecJHzXKsbz9iGm_gsjo

{
	"email": "sam@lo.agency",
    "name": "sam haris",
    "phone": "09123456789",
    "status": "Lead"
}
