DELETE http://localhost:3001/contacts/62 HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdvbHh4eEBkLmNvbSIsInN1YiI6MTA4LCJuYW1lIjoiZ29sIERvZSIsImlhdCI6MTY2Mjg4MTIzNiwiZXhwIjoxNjY1NDczMjM2fQ.kuy3cxEMYj5jGKrk1uFLZXwIXMddzGWKG9X-wIBhKIA
