GET http://localhost:3001/contacts?status=Lead&page=1&size=10 HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtlcmlvQGxvLmFnZW5jeSIsInN1YiI6MiwibmFtZSI6ImtlcmlvIERvZSIsImlhdCI6MTY2NDk2MTcwOSwiZXhwIjoxNjY3NTUzNzA5fQ.yD4ce9Pcyyl2TuXsdKfgu-rd2H3Y5x6QaCezBBvy_AM