GET http://localhost:3001/contacts/1 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpbmFAZC5jb20iLCJzdWIiOjMsIm5hbWUiOiJzaW5hIiwiaWF0IjoxNjY0MTc1MDU1LCJleHAiOjE2NjY3NjcwNTV9.SZTLj5dk51xnv9RrvpffGeKulWt9YXkM5guafaSvwsw
