GET http://localhost:3001/contacts HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZG9lLmNvbSIsInN1YiI6NDcsIm5hbWUiOiJKb2huIERvZSIsImlhdCI6MTY2MTQyMDA5OSwiZXhwIjoxNjY0MDEyMDk5fQ.EnSAZ2yb8ko7mgdlpyJ3F03k1qwEA-Q5BVh-hxO88YU