GET http://localhost:3001/contacts HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1yQGQuY29tIiwic3ViIjo3MiwibmFtZSI6ImlibSBEb2UiLCJyb2xlIjp7ImlkIjoxLCJuYW1lIjoiT3duZXIiLCJjcmVhdGVkQXQiOiIyMDIyLTEwLTIzVDAzOjEyOjUyLjkwMVoiLCJ1cGRhdGVkQXQiOiIyMDIyLTEwLTIzVDAzOjEyOjUyLjkwMVoifSwiaWF0IjoxNjY4MDUzNTAxLCJleHAiOjE2NzA2NDU1MDF9.EuKbRudtl-3O1dYQdoH3PLbwFli90BLNpEr6bit1c7E
